// <auto-generated />
using System;
using EmilioAlbornoz_ExamenP1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmilioAlbornoz_ExamenP1.Migrations
{
    [DbContext(typeof(EmilioAlbornoz_ExamenP1Context))]
    [Migration("20240424155028_CambiosBdd1")]
    partial class CambiosBdd1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmilioAlbornozBurger.Models.Pollo", b =>
                {
                    b.Property<int>("EA_PolloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EA_PolloId"));

                    b.Property<DateTime>("EA_FechadeProduccion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EA_IncluyeSalsa")
                        .HasColumnType("bit");

                    b.Property<string>("EA_Nombre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("EA_Piezas")
                        .HasColumnType("int");

                    b.Property<decimal>("EA_Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EA_PolloId");

                    b.ToTable("Pollo");
                });
#pragma warning restore 612, 618
        }
    }
}
